### PR TITLE
Left sidebar plugins + fix activeIndex prop passed to sidebar.

### PR DESCRIPTION
**Pull request by JamesAPetts**
WIP.

Works without StudyBrowser being an extension for now. Maybe it should be one though, it could be overridden, where do we draw the line?

### CODE REVIEW

**Comment by JamesAPetts** [comment]
Looks like we have a clash of windows/unix file extensions on all the images, I'll fix this when I come back to flesh this out.

**Comment by dannyrb** [comment]
Let me know when this is ready for review :+1:
I assume this is a priority because of XNAT's desire to make the left sidebar pluggable for their custom hierarchy?

**Comment by JamesAPetts** [comment]
Yeah the left sidebar is the main peice of the puzzle needed for XNAT migration to Reactified OHIF 👍 .

What's your opinion on the status of the `StudyBrowser`?
People may well want to replace it with something custom/modify it slightly (we have collapsable studies in one list in some views in XNAT, for instance), however if you modify the `StudyBrowser` you are unlikely to want the vanilla version as well, meaning this could just be something you modify at application level?

I'll try and uncommit all the images when I get in to the office haha.

**Comment by JamesAPetts** [comment]
It was easier to fix the line ending commit by rebasing from your original, PR is ready here: #2 .

**Pull request closed without merging**
